# Generated by Django 2.1.2 on 2018-10-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdiabetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='carbo_grams',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='fat_grams',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='protein_grams',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, 'not defined'), (1, 'male'), (2, 'female')], default=0),
        ),
    ]
