# Generated by Django 2.1.2 on 2018-10-03 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartdiabetes', '0002_auto_20181002_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsulinAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insulin_in_action', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='targetedlevels',
            name='insulin_in_action',
        ),
        migrations.AlterField(
            model_name='insulinratio',
            name='end_time',
            field=models.IntegerField(verbose_name='Zakres czasu do'),
        ),
        migrations.AlterField(
            model_name='insulinratio',
            name='insulin_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Przelicznik'),
        ),
        migrations.AlterField(
            model_name='insulinratio',
            name='start_time',
            field=models.IntegerField(verbose_name='Zakres czasu od'),
        ),
        migrations.AlterField(
            model_name='insulinsensitivity',
            name='end_time',
            field=models.IntegerField(verbose_name='Zakres czasu do'),
        ),
        migrations.AlterField(
            model_name='insulinsensitivity',
            name='insulin_sensitivity',
            field=models.IntegerField(verbose_name='Wrażliwość na insulinę'),
        ),
        migrations.AlterField(
            model_name='insulinsensitivity',
            name='start_time',
            field=models.IntegerField(verbose_name='Zakres czasu od'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_city',
            field=models.CharField(max_length=64, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_no',
            field=models.CharField(max_length=64, verbose_name='Numer domu'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_street',
            field=models.CharField(max_length=64, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, 'niezdefiniowana'), (1, 'mężczyzna'), (2, 'kobieta')], default=0, verbose_name='Płeć'),
        ),
        migrations.AddField(
            model_name='insulinaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
