# Generated by Django 2.1.2 on 2018-10-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdiabetes', '0003_auto_20181003_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insulinaction',
            name='insulin_in_action',
            field=models.IntegerField(verbose_name='Czas działania insuliny'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='wbt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='menu',
            name='ww',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='targetedlevels',
            name='end_time',
            field=models.IntegerField(verbose_name='Zakres czasu do'),
        ),
        migrations.AlterField(
            model_name='targetedlevels',
            name='max_level',
            field=models.IntegerField(verbose_name='Zakres docelowy do'),
        ),
        migrations.AlterField(
            model_name='targetedlevels',
            name='min_level',
            field=models.IntegerField(verbose_name='Zakres docelowy od'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, 'niezdefiniowana'), (2, 'kobieta'), (1, 'mężczyzna')], default=0, verbose_name='Płeć'),
        ),
    ]
