# Generated by Django 2.1.2 on 2018-10-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdiabetes', '0004_auto_20181003_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarymenu',
            name='carbo_grams',
            field=models.IntegerField(verbose_name='Ile gram węglowodanów'),
        ),
        migrations.AlterField(
            model_name='temporarymenu',
            name='fat_grams',
            field=models.IntegerField(verbose_name='Ile gram tłuszczy'),
        ),
        migrations.AlterField(
            model_name='temporarymenu',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Nazwa posiłku'),
        ),
        migrations.AlterField(
            model_name='temporarymenu',
            name='protein_grams',
            field=models.IntegerField(verbose_name='Ile gram białka'),
        ),
    ]
