# Generated by Django 2.1.2 on 2018-10-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdiabetes', '0006_auto_20181003_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='carbo_grams',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ile gram węglowodanów'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='fat_grams',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ile gram tłuszczy'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='protein_grams',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ile gram białka'),
        ),
        migrations.AlterField(
            model_name='temporarymenu',
            name='carbo_grams',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ile gram węglowodanów'),
        ),
        migrations.AlterField(
            model_name='temporarymenu',
            name='fat_grams',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ile gram tłuszczy'),
        ),
        migrations.AlterField(
            model_name='temporarymenu',
            name='protein_grams',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ile gram białka'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(1, 'mężczyzna'), (0, 'niezdefiniowana'), (2, 'kobieta')], default=0, verbose_name='Płeć'),
        ),
    ]
