# Generated by Django 2.1.2 on 2018-10-04 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartdiabetes', '0007_auto_20181003_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGlucoseResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InsulinInjections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction', models.BooleanField(default=0)),
                ('insulin_dose', models.FloatField(verbose_name='Dawka insuliny')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('glucose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartdiabetes.BloodGlucoseResults')),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ww', models.FloatField(blank=True, verbose_name='WW')),
                ('wbt', models.FloatField(blank=True, verbose_name='WBT')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('glucose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartdiabetes.BloodGlucoseResults')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='insulinresults',
            name='user',
        ),
        migrations.DeleteModel(
            name='InsulinResults',
        ),
        migrations.AddField(
            model_name='insulininjections',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartdiabetes.Meals'),
        ),
        migrations.AddField(
            model_name='insulininjections',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
