# Generated by Django 2.1.2 on 2018-10-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdiabetes', '0009_auto_20181004_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodglucoseresults',
            name='glucose',
            field=models.IntegerField(verbose_name='Podaj glikemie'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nazwa posiłku'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(2, 'kobieta'), (1, 'mężczyzna'), (0, 'niezdefiniowana')], default=0, verbose_name='Płeć'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('user', 'name')},
        ),
    ]
